PORT: 8080
LOG_LEVEL: 20
PRIVATE_SSH_KEY_PATH: "res/key"
REMOTE_FOLDER: "/tmp/Purpl3_RMS/"
BLACKLIST_CMD_FILE: "res/blacklistCMD.txt"
DB_PATH: 'purpl3_rms.db'
OUTPUT_TIMEOUT: 3
PUBLIC_SSH_KEY_VALUE: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQxKZrQbXNYqNK3e2iCvQcAxRBgM7P8Cg9m0z8iDjCAhNmr6HaKX4k3TsDAtHG1VqkKZ5Lo4BoU1g1cbi6RLdKKr/l6wYQ/+h8wN5wpKgW59ZJWW8v8xlT8mpYs/5zwikg+7DMDFThVno5ttvoMYPXhX+/Y0AHL5xaaXoHswbP5ZQq2pcRSsiWk2fD3n1PmFVJEL11NXcKBGYcFbbtfwhIep7Z/7akDHgfX0YnekAyknHx2GxLh2gnNtDDH/BrifnL27ZZjqm9POS2Lnxg35gUhk1ixTn1wnC/S7wIatsQAmoPzW6fyJXNq8vyGvskTWO3jAXUssVZAPF2ZWarvKTD hughbroders@Hughs-SMU-MBP.hitronhub.home" 

